baseURL = "/"
languageCode = "en-us"
title = "MVPS"
theme = "simple"
publishDir = "docs"

[[menu.main]]
  name = "Food"
  weight = -70
  url = "/food"

[[menu.main]]
  name = "About"
  weight = -70
  url = "/about"

[[menu.main]]
  name = "Drinks"
  weight = -70
  url = "/drinks"

[[menu.main]]
  name = "contact"
  weight = -60
  url = "/contact"

[params]
  description = "MVPS, gril and patio"
  author = "github.com/colorlessenergy"
